In [7]:
import numpy as np

In [15]:
#1. Array Creation:
arr_1d = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#2. Basic Operations:   Indexing and Slicing:
x = arr_1d[2]
print(x)

3


In [32]:
x = arr_2d[(0,1),:]
print(x)
#OR (not clear question)
y = arr_2d[:2, :2]
print(y)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [33]:
#2. Basic Operations:  Basic Arithmetic:
add_5_arr_1d = arr_1d + 5
print(add_5_arr_1d)

[ 6  7  8  9 10 11 12 13 14 15]


In [34]:
multp_2_arr_2d = arr_2d * 2
print(multp_2_arr_2d)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [40]:
# 3. Output Function:

# Do not know if I clearly understand the task
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

def print_array(array, message = None):
    if message:
        print(message)
    print(array)

print_array(arr2, "Below is a resulting array:")


Below is a resulting array:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# 4. Manipulation Workflow:

In [41]:
arr_1d = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
print_array(arr_1d, "Below is a resulting array:")

Below is a resulting array:
[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print_array(arr_2d, "Below is a resulting array:")

Below is a resulting array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
x = arr_1d[2]
print_array(x, "Below is a resulting array:")

Below is a resulting array:
3


In [44]:
y = arr_2d[:2, :2]
print_array(y, "Below is a resulting array:")

Below is a resulting array:
[[1 2]
 [4 5]]


In [45]:
add_5_arr_1d = arr_1d + 5
print_array(add_5_arr_1d, "Below is a resulting array:")

Below is a resulting array:
[ 6  7  8  9 10 11 12 13 14 15]


In [46]:
multp_2_arr_2d = arr_2d * 2
print_array(multp_2_arr_2d, "Below is a resulting array:")

Below is a resulting array:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
