In [657]:
# 3 Array Manipulation with Separate Output Function in NumPy

In [661]:
import numpy as np
array = np.random.randint(1, 10, size=(6, 6))

In [662]:
 print(array)

[[1 1 1 5 9 7]
 [6 1 3 2 4 2]
 [1 9 4 2 4 5]
 [6 4 1 6 1 5]
 [9 1 2 4 2 5]
 [4 8 1 9 4 6]]


In [663]:
def transpose_array(arr):
    transpose_array = arr.transpose()
    return transpose_array

In [664]:
transpose_array(array)

array([[1, 6, 1, 6, 9, 4],
       [1, 1, 9, 4, 1, 8],
       [1, 3, 4, 1, 2, 1],
       [5, 2, 2, 6, 4, 9],
       [9, 4, 4, 1, 2, 4],
       [7, 2, 5, 5, 5, 6]])

In [667]:
def reshape_array(arr):
    reshape_array = arr.reshape(3, 12)
    return reshape_array

In [668]:
reshape_array(array)

array([[1, 1, 1, 5, 9, 7, 6, 1, 3, 2, 4, 2],
       [1, 9, 4, 2, 4, 5, 6, 4, 1, 6, 1, 5],
       [9, 1, 2, 4, 2, 5, 4, 8, 1, 9, 4, 6]])

In [716]:
def split_array(arr):
    splited_array = np.array_split(arr, 3, axis=0)
    arr1 = splited_array[0]
    arr2 = splited_array[1]
    arr3 = splited_array[2]
    return arr1, arr2, arr3
#     print(splited_array[0])
#     print(splited_array[1])
#     print(splited_array[2])

In [717]:
split_array(array)

(array([[1, 1, 1, 5, 9, 7],
        [6, 1, 3, 2, 4, 2]]),
 array([[1, 9, 4, 2, 4, 5],
        [6, 4, 1, 6, 1, 5]]),
 array([[9, 1, 2, 4, 2, 5],
        [4, 8, 1, 9, 4, 6]]))

In [736]:
def concatenate_arrays(arr):
    #concatenated_array = np.concatenate((array[0], array[1], array[2]))
    concatenated_array = np.vstack((array[0:]))
    return concatenated_array

In [737]:
concatenate_arrays(split_array(array))

array([[1, 1, 1, 5, 9, 7],
       [6, 1, 3, 2, 4, 2],
       [1, 9, 4, 2, 4, 5],
       [6, 4, 1, 6, 1, 5],
       [9, 1, 2, 4, 2, 5],
       [4, 8, 1, 9, 4, 6]])